CREATE TABLE IF NOT EXISTS events (
  id    INTEGER PRIMARY KEY AUTOINCREMENT,
  hid   TEXT NOT NULL,
  ts    INTEGER NOT NULL,
  type  TEXT NOT NULL,
  by    TEXT NOT NULL,
  note  TEXT,
  -- Per-cat scope. 'primary' = the household's first cat (the silent
  -- default for single-cat households). When the firmware learns to
  -- pass per-cat IDs (currently single-cat across the wire), values
  -- will be the stable Cat::id from CatRoster.
  cat   TEXT NOT NULL DEFAULT 'primary',
  -- Idempotency key — 128-bit hex UUID generated by the firmware
  -- and sent on POST /api/feed. Same id replayed (e.g. pending-queue
  -- retry after a network timeout the server actually processed)
  -- silently dedups via the unique index. NULL allowed for legacy
  -- rows from before this column existed.
  event_id TEXT
);
CREATE INDEX        IF NOT EXISTS idx_hid_ts     ON events(hid, ts DESC);
CREATE INDEX        IF NOT EXISTS idx_hid_cat_ts ON events(hid, cat, ts DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_event_id   ON events(event_id);

-- ── Households ────────────────────────────────────────────────────
-- One row per home. After migration 0004, `hid` IS the home name —
-- a user-chosen unique identifier picked at setup time (e.g.
-- "Smith Family", "kitchen"). PIN is required to access the web app
-- and stored as PBKDF2-SHA256(plain_pin, salt, 100k iters). Salt
-- and hash are 32 bytes each (hex-encoded → 64 chars).
--
-- The `name` column is a leftover from migration 0003 (when name +
-- hid were separate). Current code doesn't read or write it; left
-- in place to avoid a destructive migration. Treat as deprecated —
-- always use `hid` as the display name.
CREATE TABLE IF NOT EXISTS households (
  hid        TEXT PRIMARY KEY,
  pin_salt   TEXT NOT NULL,
  pin_hash   TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  name       TEXT NOT NULL DEFAULT '',  -- deprecated; see migration 0004 notes
  -- Sync support (migration 0005). updated_at drives LWW; is_deleted
  -- is the tombstone the webapp + firmware filter on for active sets.
  updated_at INTEGER NOT NULL DEFAULT 0,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  -- Phase E (migration 0009). How often a paired device should sync
  -- when idle. Range 3600 (1h) .. 86400 (24h); enforced in the
  -- /api/home/settings PATCH handler. Devices read this from the
  -- /api/sync response on every successful sync and cache it in NVS.
  sync_interval_sec INTEGER NOT NULL DEFAULT 14400
);

-- ── Devices ───────────────────────────────────────────────────────
-- Maps a physical FeedMe device (its firmware-generated hid like
-- feedme-a8b3c1d4e5f6) to a home (households.hid). Many-to-one:
-- multiple devices can pair into the same home. Populated by
-- /api/auth/setup (when the user creates a home from a device QR)
-- and /api/auth/login (when a user signs into an existing home from
-- a fresh device's QR — "claim").
--
-- Firmware-facing endpoints (/api/feed, /api/state, /api/history)
-- accept the firmware's hid in their payload and translate it via
-- this table to the home's hid before reading/writing the events
-- table. If a device hasn't been claimed, the lookup falls back to
-- treating the device hid as the home hid — preserves single-device
-- legacy behaviour with zero firmware changes required.
CREATE TABLE IF NOT EXISTS devices (
  device_id  TEXT PRIMARY KEY,
  home_hid   TEXT NOT NULL,
  joined_at  INTEGER NOT NULL,
  -- Sync support (migration 0005). created_at + updated_at duplicate
  -- joined_at on first insert; updated_at bumps if the same device
  -- re-pairs into the same home after a soft-delete.
  created_at INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL DEFAULT 0,
  is_deleted INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_devices_home_hid ON devices(home_hid);

-- ── Cats ──────────────────────────────────────────────────────────
-- Mirrors the firmware's CatRoster. slot_id is the stable uint8_t
-- from the device (0..3 today, MAX_CATS=4) — composite PK with hid
-- so multiple households can each have a slot 0. Soft delete via
-- deleted_at preserves event-attribution lookups for cats removed
-- from the active roster.
CREATE TABLE IF NOT EXISTS cats (
  hid                  TEXT NOT NULL,
  slot_id              INTEGER NOT NULL,
  name                 TEXT NOT NULL,
  color                INTEGER NOT NULL DEFAULT 0,         -- 0xRRGGBB; 0 = "auto"
  slug                 TEXT NOT NULL DEFAULT 'C2',
  default_portion_g    INTEGER NOT NULL DEFAULT 40,
  hungry_threshold_sec INTEGER NOT NULL DEFAULT 18000,     -- 5 hours
  deleted_at           INTEGER,                            -- legacy soft-delete (Phase 2 era)
  -- Sync support (migration 0005). is_deleted is the canonical
  -- tombstone going forward; deleted_at is kept for back-compat
  -- with code paths that haven't migrated yet.
  created_at           INTEGER NOT NULL DEFAULT 1735689600,
  updated_at           INTEGER NOT NULL DEFAULT 1735689600,
  is_deleted           INTEGER NOT NULL DEFAULT 0,
  -- Per-cat meal schedule (migration 0007). JSON array of 4 hours
  -- 0..23 matching firmware's MealSchedule (Breakfast / Lunch /
  -- Dinner / Treat). Sync round-trips this verbatim.
  schedule_hours       TEXT NOT NULL DEFAULT '[7,12,18,21]',
  PRIMARY KEY (hid, slot_id)
);

-- ── Users ─────────────────────────────────────────────────────────
-- Mirrors the firmware's UserRoster. Same composite-PK pattern as
-- cats. Soft delete keeps event `by` attributions stable.
CREATE TABLE IF NOT EXISTS users (
  hid        TEXT NOT NULL,
  slot_id    INTEGER NOT NULL,
  name       TEXT NOT NULL,
  color      INTEGER NOT NULL DEFAULT 0,                   -- 0xRRGGBB; 0 = "auto"
  deleted_at INTEGER,                                      -- legacy soft-delete (Phase 2 era)
  -- Sync support (migration 0005). See cats above for the same
  -- rationale on is_deleted vs deleted_at coexistence.
  created_at INTEGER NOT NULL DEFAULT 1735689600,
  updated_at INTEGER NOT NULL DEFAULT 1735689600,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (hid, slot_id)
);

-- ── Sync support tables (migration 0006) ─────────────────────────
-- See docs/sync-implementation-handoff.md §4.2.

CREATE TABLE IF NOT EXISTS pending_pairings (
  device_id     TEXT PRIMARY KEY,
  requested_at  INTEGER NOT NULL,
  expires_at    INTEGER NOT NULL,         -- requested_at + 180
  home_hid      TEXT,
  confirmed_at  INTEGER,
  device_token  TEXT,
  cancelled_at  INTEGER
);

CREATE TABLE IF NOT EXISTS pairings (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  device_id     TEXT NOT NULL,
  home_hid      TEXT NOT NULL,
  created_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL,
  is_deleted    INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_pairings_device ON pairings(device_id);
CREATE INDEX IF NOT EXISTS idx_pairings_home   ON pairings(home_hid);

CREATE TABLE IF NOT EXISTS sync_logs (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  home_hid        TEXT NOT NULL,
  device_id       TEXT NOT NULL,
  ts              INTEGER NOT NULL,
  result          TEXT NOT NULL,
  error_message   TEXT,
  entities_in     INTEGER NOT NULL DEFAULT 0,
  entities_out    INTEGER NOT NULL DEFAULT 0,
  conflicts       INTEGER NOT NULL DEFAULT 0,
  duration_ms     INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_sync_logs_home_ts ON sync_logs(home_hid, ts DESC);

-- ── Migrations ────────────────────────────────────────────────────
-- This file is the CANONICAL FULL SCHEMA — what a brand-new database
-- should look like. For existing databases that need to catch up to
-- the current state, see `migrations/` and the README there.
--
--   migrations/0001_legacy_event_cols.sql  — adds `cat` + `event_id`
--                                            to events for pre-Phase-2
--                                            databases. Skip if the
--                                            DB was created against
--                                            a recent schema.sql.
--   migrations/0002_webapp_tables.sql      — household / cats / users
--                                            tables for the web app.
--
-- Apply old → new with the npm scripts:
--   npm run db:migrate:0001:remote
--   npm run db:migrate:0002:remote
--
-- DON'T run `db:apply:remote` (this file) on an old DB that's missing
-- the events.event_id column — the `CREATE UNIQUE INDEX idx_event_id`
-- below references that column and SQLite will error out. Use the
-- migration files for incremental upgrades.
