"""Convert cat silhouette PNGs from firmware/design/cats4/ into LVGL v8.4
lv_img_dsc_t C arrays under firmware/src/assets/cats/.

Output format: CF_TRUE_COLOR_ALPHA — 16-bit RGB565 + 8-bit alpha per pixel.
On a 130x130 cat that's 130*130*3 = 50.7 KB; an 88x88 is 23.2 KB. The five
mood cats at two sizes total ≈ 370 KB which is fine on our 16 MB flash.

Why this script instead of the online LVGL tool: scriptable, reproducible,
runs without browser interaction, fits the existing PIO build flow. Output
format is byte-compatible with the v8.4 image converter on
https://lvgl.io/tools/imageconverter (we matched the layout exactly).

Usage (from repo root):
    python firmware/scripts/convert_cats.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Iterable

try:
    from PIL import Image
except ImportError:
    sys.stderr.write(
        "ERROR: Pillow is required. Install with: pip install pillow\n"
    )
    sys.exit(1)


# ── Configuration ─────────────────────────────────────────────────────────
HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent  # repo root
SRC_DIR = REPO / "firmware" / "design" / "cats4"
DST_DIR = REPO / "firmware" / "src" / "assets" / "cats"

# 5 mood cats, per docs/feedmeknob-plan.md decision (5 cats now, 12 later).
MOOD_CATS = ["B1", "B2", "B3", "C2", "C4"]

# Sizes used by the screens. 130 px = Idle hero, 88 px = Feed Confirm.
SIZES = [130, 88]

# Use the white-on-transparent variant — they render against the dark
# Aubergine background. Pixels are essentially (255,255,255,A); we
# preserve A to keep anti-aliased edges crisp.
VARIANT = "white"


# ── RGB565 packing ────────────────────────────────────────────────────────
def rgb565(r: int, g: int, b: int) -> int:
    """Pack 8-8-8 RGB into 16-bit 5-6-5."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


# ── Source loading & resizing ─────────────────────────────────────────────
def load_and_resize(path: Path, size: int) -> Image.Image:
    img = Image.open(path).convert("RGBA")
    return img.resize((size, size), Image.LANCZOS)


# ── LVGL CF_TRUE_COLOR_ALPHA byte serialization ───────────────────────────
# Per LVGL v8.4 with LV_COLOR_DEPTH=16 (and LV_COLOR_16_SWAP=0 in our
# lv_conf.h): each pixel is stored as 3 bytes — low byte of RGB565, high
# byte of RGB565, then alpha. The renderer reads this back as a struct
# of (uint16_t color, uint8_t alpha).
def pack_pixels(img: Image.Image) -> bytes:
    out = bytearray()
    pixels = img.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = pixels[x, y]
            c = rgb565(r, g, b)
            out.append(c & 0xFF)        # low byte first (LVGL native)
            out.append((c >> 8) & 0xFF) # high byte
            out.append(a)               # alpha
    return bytes(out)


# ── C-array emission ──────────────────────────────────────────────────────
HEADER = """// Auto-generated by firmware/scripts/convert_cats.py — do not edit by hand.
//
// Source: firmware/design/cats4/{slug}-{variant}.png
// Format: LVGL CF_TRUE_COLOR_ALPHA at {size}x{size}
//   3 bytes per pixel (low/high RGB565 + 1-byte alpha).

#include <lvgl.h>

"""


def emit_c(slug: str, size: int, payload: bytes, dst: Path) -> None:
    var = f"cat_{slug.lower()}_{size}"
    dst.parent.mkdir(parents=True, exist_ok=True)
    with dst.open("w", encoding="utf-8") as f:
        f.write(HEADER.format(slug=slug, variant=VARIANT, size=size))

        # Pixel-data byte array, 16 bytes per row for readability.
        f.write(f"static const LV_ATTRIBUTE_LARGE_CONST uint8_t "
                f"{var}_data[] LV_ATTRIBUTE_MEM_ALIGN = {{\n")
        for i in range(0, len(payload), 16):
            chunk = payload[i:i + 16]
            f.write("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n\n")

        # lv_img_dsc_t descriptor matching the v8.4 layout.
        f.write(f"const lv_img_dsc_t {var} = {{\n")
        f.write("    .header = {\n")
        f.write("        .cf = LV_IMG_CF_TRUE_COLOR_ALPHA,\n")
        f.write("        .always_zero = 0,\n")
        f.write("        .reserved = 0,\n")
        f.write(f"        .w = {size},\n")
        f.write(f"        .h = {size},\n")
        f.write("    },\n")
        f.write(f"    .data_size = {len(payload)},\n")
        f.write(f"    .data = {var}_data,\n")
        f.write("};\n")


# ── Manifest header ───────────────────────────────────────────────────────
def emit_manifest(slugs: Iterable[str], sizes: Iterable[int],
                  manifest_path: Path) -> None:
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    with manifest_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by firmware/scripts/convert_cats.py.\n")
        f.write("//\n")
        f.write("// Forward declarations of every embedded cat lv_img_dsc_t,\n")
        f.write("// so adapters can `#include \"assets/cats/cats.h\"` and\n")
        f.write("// reference any cat without pulling in a per-cat .h file.\n\n")
        f.write("#pragma once\n\n")
        f.write("#include <lvgl.h>\n\n")
        f.write("extern \"C\" {\n")
        for slug in slugs:
            for size in sizes:
                f.write(f"extern const lv_img_dsc_t cat_{slug.lower()}_{size};\n")
        f.write("}\n")


# ── Driver ────────────────────────────────────────────────────────────────
def main() -> int:
    if not SRC_DIR.is_dir():
        sys.stderr.write(f"ERROR: source dir not found: {SRC_DIR}\n")
        sys.stderr.write(
            "Did you copy firmware/design/cats4/ from the handoff bundle?\n"
        )
        return 1

    print(f"[cats] source : {SRC_DIR}")
    print(f"[cats] dest   : {DST_DIR}")
    print(f"[cats] cats   : {', '.join(MOOD_CATS)}")
    print(f"[cats] sizes  : {SIZES}")

    total_bytes = 0
    for slug in MOOD_CATS:
        png = SRC_DIR / f"{slug}-{VARIANT}.png"
        if not png.is_file():
            sys.stderr.write(f"WARN: missing source {png}\n")
            continue
        for size in SIZES:
            img = load_and_resize(png, size)
            payload = pack_pixels(img)
            out = DST_DIR / f"cat_{slug.lower()}_{size}.c"
            emit_c(slug, size, payload, out)
            total_bytes += len(payload)
            print(f"  {slug} {size:3d}px  ->  "
                  f"{out.relative_to(REPO)}  ({len(payload):>6d} B)")

    emit_manifest(MOOD_CATS, SIZES, DST_DIR / "cats.h")
    print(f"[cats] total payload: {total_bytes/1024:.1f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
