// Auto-generated by firmware/scripts/convert_cats.py.
//
// Forward declarations of every embedded cat lv_img_dsc_t,
// so adapters can `#include "assets/cats/cats.h"` and
// reference any cat without pulling in a per-cat .h file.

#pragma once

#include <lvgl.h>

extern "C" {
extern const lv_img_dsc_t cat_b1_130;
extern const lv_img_dsc_t cat_b1_88;
extern const lv_img_dsc_t cat_b2_130;
extern const lv_img_dsc_t cat_b2_88;
extern const lv_img_dsc_t cat_b3_130;
extern const lv_img_dsc_t cat_b3_88;
extern const lv_img_dsc_t cat_c2_130;
extern const lv_img_dsc_t cat_c2_88;
extern const lv_img_dsc_t cat_c4_130;
extern const lv_img_dsc_t cat_c4_88;
}
